2020-02-04 18:25:04.010413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:25:04.016318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:04.016673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:04.018792: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:04.020561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:04.021055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:04.023462: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:04.025301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:04.032313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:04.033489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:04.033979: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:25:04.056755: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:25:04.063102: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x63af6c0 executing computations on platform Host. Devices:
2020-02-04 18:25:04.063150: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:25:04.208441: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6412710 executing computations on platform CUDA. Devices:
2020-02-04 18:25:04.208496: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:25:04.209358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:04.209442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:04.209473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:04.209499: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:04.209526: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:04.209551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:04.209577: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:04.209605: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:04.210831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:04.210909: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:04.213016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:25:04.213046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:25:04.213071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:25:04.214473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 152, in <module>
    epochs=1, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
2020-02-04 18:25:09.538825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:25:09.544305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:09.544642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:09.546629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:09.548305: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:09.548767: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:09.550988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:09.552882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:09.559423: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:09.560487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:09.560926: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:25:09.581634: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:25:09.585514: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x601ee50 executing computations on platform Host. Devices:
2020-02-04 18:25:09.585569: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:25:09.718976: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6081ea0 executing computations on platform CUDA. Devices:
2020-02-04 18:25:09.719024: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:25:09.719576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:09.719649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:09.719673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:09.719693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:09.719712: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:09.719732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:09.719751: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:09.719771: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:09.720528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:09.720588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:09.722500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:25:09.722527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:25:09.722539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:25:09.723910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 152, in <module>
    epochs=1, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
2020-02-04 18:25:14.878456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:25:14.883956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:14.884340: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:14.886414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:14.888227: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:14.888731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:14.891112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:14.892960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:14.898480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:14.899514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:14.899967: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:25:14.925649: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:25:14.930502: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6c76e50 executing computations on platform Host. Devices:
2020-02-04 18:25:14.930547: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:25:15.059042: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6cd9eb0 executing computations on platform CUDA. Devices:
2020-02-04 18:25:15.059083: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:25:15.059584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:25:15.059657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:15.059680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:25:15.059697: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:25:15.059715: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:25:15.059732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:25:15.059750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:25:15.059768: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:25:15.060453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:25:15.060500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:25:15.062409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:25:15.062437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:25:15.062450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:25:15.063820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 152, in <module>
    epochs=1, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
2020-02-04 18:27:37.648664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:27:37.654592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:37.654977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:37.657434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:37.659545: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:37.660078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:37.662644: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:37.664636: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:37.670675: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:37.671787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:37.672255: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:27:37.693804: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:27:37.699338: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6f9d220 executing computations on platform Host. Devices:
2020-02-04 18:27:37.699401: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:27:37.801412: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7000210 executing computations on platform CUDA. Devices:
2020-02-04 18:27:37.801464: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:27:37.802169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:37.802243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:37.802269: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:37.802292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:37.802330: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:37.802353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:37.802374: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:37.802397: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:37.803395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:37.803456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:37.805282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:27:37.805312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:27:37.805324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:27:37.806691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 180, in <module>
    epochs=100, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
2020-02-04 18:27:43.382589: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:27:43.387996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:43.388380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:43.390561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:43.392465: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:43.392952: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:43.395399: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:43.397250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:43.402894: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:43.403996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:43.404495: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:27:43.429946: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:27:43.434880: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x62e0c50 executing computations on platform Host. Devices:
2020-02-04 18:27:43.434901: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:27:43.558797: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6343c80 executing computations on platform CUDA. Devices:
2020-02-04 18:27:43.558854: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:27:43.559704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:43.559785: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:43.559816: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:43.559843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:43.559869: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:43.559895: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:43.559922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:43.559948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:43.561222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:43.561296: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:43.563282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:27:43.563309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:27:43.563322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:27:43.564693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 180, in <module>
    epochs=100, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
2020-02-04 18:27:49.038138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 18:27:49.043983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:49.044381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:49.046545: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:49.048320: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:49.048831: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:49.051276: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:49.053104: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:49.059916: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:49.061054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:49.061518: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 18:27:49.080025: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400265000 Hz
2020-02-04 18:27:49.085495: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x618d8c0 executing computations on platform Host. Devices:
2020-02-04 18:27:49.085540: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-02-04 18:27:49.232634: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x61f0920 executing computations on platform CUDA. Devices:
2020-02-04 18:27:49.232671: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-04 18:27:49.233529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
2020-02-04 18:27:49.233630: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:49.233666: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-02-04 18:27:49.233697: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-02-04 18:27:49.233728: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-02-04 18:27:49.233759: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-02-04 18:27:49.233789: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-02-04 18:27:49.233836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 18:27:49.235061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-04 18:27:49.235148: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-02-04 18:27:49.237186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 18:27:49.237214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-04 18:27:49.237227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-04 18:27:49.238613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 201 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
0 1
Traceback (most recent call last):
  File "ILI_Forecast.py", line 180, in <module>
    epochs=100, batch_size=BATCH_SIZE)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 708, in fit
    func = self._select_training_loop(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 500, in _select_training_loop
    valid_adapter = data_adapter.select_data_adapter(inputs, None)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 647, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 453, in can_handle
    handles_x = ListsOfScalarsDataAdapter._is_list_of_scalars(x)
  File "/home/mimorris/tf2_env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 464, in _is_list_of_scalars
    return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range
